version: '3.3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    #image: margarita2105/foodgram:latest
    restart: always
    command: sh -c "python manage.py migrate && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/code/static/
      - media_volume:/code/media/

    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - 80:80
    depends_on:
      - web
    #links:
    #  - web
    environment: 
      - NGINX_HOST=127.0.0.1 
      - NGINX_PORT=80
